name: build-mac

on:
  workflow_dispatch:

jobs:
  build-macos-arm64:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install build tooling (latest)
        run: |
          pip install --upgrade pyinstaller pyinstaller-hooks-contrib

      - name: Clean
        run: |
          rm -rf build dist   # DO NOT delete BomDiff.spec

      - name: Verify spec & hook
        run: |
          echo "=== requirements.txt ==="; cat requirements.txt
          echo "=== numpy installed path ==="
          python - <<'PY'
import numpy, sys
print("numpy.__file__ =", numpy.__file__)
PY
          echo "=== BomDiff.spec (first 140 lines) ==="
          sed -n '1,140p' BomDiff.spec
          echo "=== runtime_fix_numpy.py ==="
          sed -n '1,140p' runtime_fix_numpy.py || echo "missing"
      - name: Build (DEBUG)
        run: |
          pyinstaller --log-level=DEBUG --clean BomDiff.spec
      - name: Debug numpy artifacts
        run: |
          echo "--- core extension(s) ---"
          find dist/BomDiff.app -name "_multiarray_umath*.so" || echo "NO core so"
          echo "--- any numpy/setup.py ---"
          find dist/BomDiff.app -path "*/numpy/setup.py" -print || echo "None"
          echo "--- any numpy/pyproject.toml ---"
          find dist/BomDiff.app -path "*/numpy/pyproject.toml" -print || echo "None"
          echo "--- list numpy/core (first 30) ---"
          find dist/BomDiff.app -path "*/numpy/core" -type d -exec ls -1 {} \; | head -n 30 || true
      - name: Ad-hoc sign
        run: |
          codesign --force --deep -s - dist/BomDiff.app || true

      - name: Add default.env + DMG
        run: |
          echo "NS_ACCOUNT_REALM=\nNS_REST_DOMAIN=\nNS_CONSUMER_KEY=\nNS_CONSUMER_SECRET=\nNS_TOKEN_ID=\nNS_TOKEN_SECRET=" > dist/default.env
          cd dist
          mkdir dmgroot
          cp -R BomDiff.app dmgroot/
          cp default.env dmgroot/
          hdiutil create -volname "BomDiff" -srcfolder dmgroot -ov -format UDZO BomDiff-macOS-arm64.dmg

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: BomDiff-macOS-arm64-dmg
          path: dist/BomDiff-macOS-arm64.dmg